# Generated by Django 5.0.6 on 2026-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='О компании', max_length=128)),
                ('title_en', models.CharField(default='About the company', max_length=128)),
                ('text_ru', models.TextField(default='Инжиниринговая компания полного цикла «Микротерм Плюс» успешно специализируется на проектировании и технической разработке в области промышленной автоматизации с 2002 года. За прошедшие годы, мы достигли больших успехов, реализовали множество масштабных проектов, получили ценный опыт и наработали тесные партнерские отношения со многими российскими и иностранными компаниями. Но мы не останавливаемся на достигнутом! Мы растем, становимся продуктивнее и продолжаем аккумулировать экспертный опыт, чтобы передавать его нашим заказчикам. Наша цель стать еще более эффективной компанией, для реализации новых амбициозных задач, придерживаясь высочайших стандартов качества.\n\nОснова успеха нашей компании — это сплоченная команда. Профессионалы, нацеленные на высокий результат, которые любят свою профессию, постоянно развиваются и изучают новые технологии. Из заслуг каждого состоит наш общий успех.\n\nНовая санкционная реальность создает целый ряд ограничений. Перед российскими производителями встал вопрос о выборе стратегии дальнейшего развития. Значительная часть устоявшихся подходов в инжиниринге требует пересмотра привычных решений. Имея многолетний практический опыт, мы готовы поддержать своих заказчиков в вопросах импортонезависимости в эксплуатации иностранного оборудования и систем, а также их дальнейшей модернизации.', help_text='Разделяйте параграфы пустой строкой')),
                ('text_en', models.TextField(default="Microterm Plus, a full-cycle engineering company, has been successfully specializing in design and technical development in the field of industrial automation since 2002. Over the years, we have achieved great success, implemented many large-scale projects, gained valuable experience and built close partnerships with many Russian and foreign companies. But we do not rest on our laurels! We grow, become more productive and continue to accumulate expert experience to pass it on to our customers. Our goal is to become an even more efficient company for implementing new ambitious tasks while adhering to the highest quality standards.\n\nThe foundation of our company's success is a cohesive team. Professionals focused on high results who love their profession, constantly develop and study new technologies. Our common success consists of the merits of each.\n\nThe new sanctions reality creates a number of restrictions. Russian manufacturers are faced with the question of choosing a strategy for further development. A significant part of the established approaches in engineering requires a revision of habitual solutions. With many years of practical experience, we are ready to support our customers in matters of import independence in the operation of foreign equipment and systems, as well as their further modernization.", help_text='Separate paragraphs with an empty line')),
                ('signature_ru', models.TextField(default='Генеральный директор ООО «Микротерм Плюс»\nАтясов Олег Валерьевич')),
                ('signature_en', models.TextField(default='General Director of Microterm Plus LLC\nAtyasov Oleg Valerievich')),
                ('industry_title_ru', models.CharField(default='Индустрии и география реализованных проектов', max_length=255)),
                ('industry_title_en', models.CharField(default='Industries and geography of completed projects', max_length=255)),
                ('industries_ru', models.TextField(default='Промышленность строительных материалов\nЛесообрабатывающая промышленность\nПроизводство подъемно-транспортного оборудования\nМашиностроение и металлообработка\nГорнодобывающая промышленность\nНефтехимическая промышленность\nТранспортные узлы и терминалы\nУгольная промышленность\nПищевая промышленность\nЛегкая промышленность\nЭлектроэнергетика', help_text='Каждая индустрия с новой строки')),
                ('industries_en', models.TextField(default='Construction materials industry\nWoodworking industry\nLifting and transport equipment manufacturing\nMechanical engineering and metalworking\nMining industry\nPetrochemical industry\nTransport hubs and terminals\nCoal industry\nFood industry\nLight industry\nElectric power industry', help_text='One industry per line')),
                ('mt_today_title_ru', models.CharField(default='МИКРОТЕРМ ПЛЮС сегодня', max_length=128)),
                ('mt_today_title_en', models.CharField(default='MICROTERM PLUS today', max_length=128)),
                ('mt_today_tiles_ru', models.TextField(default='20 лет на рынке автоматизации\nБолее 200 реализованных проектов\nГеография проектов охватывает всю Россию\nТочное соблюдение сроков производства работ\nОткрытый диалог с заказчиком\nКачество с мировым именем\nКвалифицированные инженерные кадры\nСертификация по международным стандартам', help_text='Один пункт на строку')),
                ('mt_today_tiles_en', models.TextField(default='20 years on the automation market\nMore than 200 completed projects\nProject geography covers all of Russia\nStrict adherence to work schedules\nOpen dialogue with the customer\nWorld-class quality\nQualified engineering personnel\nCertification to international standards', help_text='One item per line')),
                ('certs_title_ru', models.CharField(default='Сертификаты и благодарственные письма', max_length=255)),
                ('certs_title_en', models.CharField(default='Certificates and letters of gratitude', max_length=255)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page (singleton)',
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='Производство грузоподъемных кранов', max_length=255)),
                ('title_en', models.CharField(default='Manufacturing of lifting cranes', max_length=255)),
                ('description_ru', models.TextField(default='Компания «КРАН-ДВ» имеет производственные и инжиниринговые мощности для выполнения крановых проектов различного уровня сложности.')),
                ('description_en', models.TextField(default='KRAN-DV has the production and engineering capacity to deliver crane projects of any complexity.')),
                ('cta_label_ru', models.CharField(default='Узнать подробнее', max_length=64)),
                ('cta_label_en', models.CharField(default='Learn more', max_length=64)),
            ],
            options={
                'verbose_name': 'Hero block',
                'verbose_name_plural': 'Hero block (singleton)',
            },
        ),
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home project',
                'verbose_name_plural': 'Home projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home service',
                'verbose_name_plural': 'Home services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128)),
                ('image', models.CharField(help_text='Path like /images/dvkran/2023__09__product-1.png', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_ru', models.CharField(default='Автоматизация технологических процессов', max_length=255)),
                ('case_en', models.CharField(default='Automation of technological processes', max_length=255)),
                ('case_en_label', models.CharField(default='Machinery Modification', max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project item',
                'verbose_name_plural': 'Project items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProviderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='Ответственный поставщик', max_length=128)),
                ('title_en', models.CharField(default='Responsible supplier', max_length=128)),
                ('paragraphs_ru', models.TextField(default='На территории регионов Дальнего Востока.\n\nКомпания «КРАН-ДВ» находится в Хабаровске. Это обеспечивает оперативную коммуникацию и логистику с Заказчиком со всего ДФО.\n\nЕсли вы заинтересованы в нашей продукции, отправляйте завки на нашу электронную почту и получите быстрый ответ.', help_text='Разделяйте параграфы пустой строкой')),
                ('paragraphs_en', models.TextField(default='In the regions of the Far East.\n\nKRAN-DV is located in Khabarovsk. This provides prompt communication and logistics with customers across the entire Far Eastern Federal District.\n\nIf you are interested in our products, send requests to our e-mail and get a quick response.', help_text='Separate paragraphs with an empty line')),
            ],
            options={
                'verbose_name': 'Provider block',
                'verbose_name_plural': 'Provider block (singleton)',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service item',
                'verbose_name_plural': 'Service items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='7 4212 54-41-95', max_length=64)),
                ('phone_additional', models.CharField(default='+7-924-108-58-70', max_length=64)),
                ('email', models.EmailField(default='kran-dv@microtermplus.ru', max_length=254)),
                ('email_office', models.EmailField(default='office@microtermplus.ru', max_length=254)),
                ('address_footer_ru', models.CharField(default='680001, г. Хабаровск, ул. Монтажная, 30, строение А, офис 21', max_length=255)),
                ('address_footer_en', models.CharField(default='680001, Khabarovsk, Montazhnaya st., 30, building A, office 21', max_length=255)),
                ('address_office_ru', models.CharField(default='680012 г. Хабаровск, ул. Флегонтова, 27', max_length=255)),
                ('address_office_en', models.CharField(default='680012 Khabarovsk, Flegontova st., 27', max_length=255)),
                ('copyright_ru', models.CharField(default='2023 @ Все права защищены.', max_length=128)),
                ('copyright_en', models.CharField(default='2023 @ All rights reserved.', max_length=128)),
                ('reference_list_url', models.URLField(default='https://drive.google.com/file/d/1HalIDIAwc5oqhoHxim3A78mnr8v51ahx/view')),
                ('yandex_map_src', models.URLField(default='https://yandex.ru/map-widget/v1/?um=constructor%3Aa5577eaa4f3e4b688a0146ae51309a8d1cba1d6d711c23dc71bdca3efcdc0854&source=constructor')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings (singleton)',
            },
        ),
    ]
